author: 'hozlucas28'
name: 'Check title of a pull request'
description: 'Check if the title of a pull request is correct'

runs:
  using: 'node20'
  main: 'main.js'

inputs:
  title:
    description: 'Title of the pull request'
    required: true
