author: 'hozlucas28'
name: 'Check title of the pull request'
description: 'Check if the title of the pull request is correct'

runs:
  using: 'node20'
  main: 'main.js'

inputs:
  title:
    description: 'Pull request title'
    required: true
