name: 'Check pull request'

on:
  pull_request:
    types: [opened, reopened, edited, synchronize]

jobs:
  pull-request-changed-files:
    runs-on: ubuntu-latest
    outputs:
      changed-files: ${{ steps.changed-files.outputs.all_changed_and_modified_files }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Get pull request changed files
        id: changed-files
        uses: tj-actions/changed-files@v42

  check-pull-request-title:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Check pull request title
        uses: ./.github/actions/check-pull-request-title
        with:
          title: ${{ github.event.pull_request.title }}

  check-pull-request-changed-files:
    needs: pull-request-changed-files
    runs-on: ubuntu-latest
    outputs:
      changed-file: ${{ steps.changed-files.outputs.changed-file }}
    steps:
      - uses: actions/checkout@v4
      - name: Check pull request changed files
        id: changed-files
        uses: ./.github/actions/check-pull-request-changed-files
        with:
          changed-files: ${{ needs.pull-request-changed-files.outputs.changed-files }}
